db: cloud
add: localhost
dbport: 3306
spring:
  profiles:
    include: druid,mybatisplus,httpclient
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${add}:${dbport}/${db}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&tinyIntlisBit=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 2864929031
  servlet:
    multipart:
      enabled: true
      max-file-size: 5242880
#mybatis-plus:
#  type-handlers-package: com.cloud.myspringcloud.typehandler
